app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', 'HomeController@showWelcome');
Route::get('dashboard', function(){
	$heading = 'Dashboard';
	$sub_heading = 'Overview';
	return View::make('dashboard', compact('heading', 'sub_heading'));

});
Route::resource('employees', 'EmployeesController');
Route::resource('laptops', 'LaptopsController');
Route::resource('memos', 'MemosController');

app/models/Employee.php
<?php

class Employee extends Eloquent {

	protected $table = 'employees';

	protected $guarded = array();

	public static $rules = array(
		'employer'			=> 'required',
		'id_number'			=> 'required',
		'first_name'		=> 'required',
		'middle_name'		=> 'required',
		'last_name'			=> 'required',
		'date_hired'		=> 'required',
		'contract_period'	=> '',
		'probitionary_date'	=> '',
		'permanency_date'	=> '',
		'designation'		=> 'required',
		'department'		=> 'required',
		'email'				=> '',
		'contact_number'	=> '',
		'gender'			=> '',
		'civil_status'		=> '',
		'dependents'		=> '',
		'hmo'				=> '',
		'sss'				=> '',
		'philhealth'		=> '',
		'pagibig'			=> '',
		'tin'				=> '',
		'date_of_birth'		=> '',
		'home_address'		=> '',
		'emergency_contact'	=> '',
		'emergency_number'	=> ''
	);

	public function memos()
	{
		return $this->hasMany('Memo');
	}
}

app/controllers/EmployeesController.php
<?php

class EmployeesController extends BaseController {

	/**
	 * Employee Repository
	 *
	 * @var Employee
	 */
	protected $employee;

	public function __construct(Employee $employee)
	{
		$this->employee = $employee;
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$employees = $this->employee->all();
		$heading = 'Employees';
		$sub_heading = 'Master List';
		return View::make('employees.index', compact('employees', 'heading', 'sub_heading'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$heading = 'Employees';
		$sub_heading = 'New Entry';
		return View::make('employees.create', compact('heading', 'sub_heading'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$input = Input::all();
		$validation = Validator::make($input, Employee::$rules);

		if ($validation->passes())
		{
			$this->employee->create($input);

			return Redirect::route('employees.index');
		}

		return Redirect::route('employees.create')
			->withInput()
			->withErrors($validation)
			->with('message', 'There were validation errors.');
	}

	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$employee = $this->employee->findOrFail($id);
		$heading = $employee->last_name.', '.$employee->first_name.' '.$employee->middle_name;
		$sub_heading = 'Detailed Information';
		return View::make('employees.show', compact('employee', 'heading', 'sub_heading'));
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$employee = $this->employee->find($id);

		if (is_null($employee))
		{
			return Redirect::route('employees.index');
		}
		$heading = $employee->last_name.', '.$employee->first_name.' '.$employee->middle_name;
		$sub_heading = 'Edit';
		return View::make('employees.edit', compact('employee', 'heading', 'sub_heading'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$input = array_except(Input::all(), '_method');
		$validation = Validator::make($input, Employee::$rules);

		if ($validation->passes())
		{
			$employee = $this->employee->find($id);
			$employee->update($input);

			return Redirect::route('employees.show', $id);
		}

		return Redirect::route('employees.edit', $id)
			->withInput()
			->withErrors($validation)
			->with('message', 'There were validation errors.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$this->employee->find($id)->delete();
		return Redirect::route('employees.index');
	}

}

app/views/employees/create.blade.php
@extends('layouts.scaffold')

@section('main')

<h1 class="">
    <span class="pull-left">
         <!-- <a href="/laptops/create" class="btn btn-flat btn-default"><i class="fa fa-plus fa-fw"></i></a> -->
        <a href="/employees" class="pull-left"><i class="fa fa-angle-left fa-fw">&nbsp;</i></a>
    </span>
    {{ $heading }} <small>{{ $sub_heading }}</small>
    <span class="pull-right">
         <!-- <a href="/employees/create" class="btn btn-flat btn-default"><i class="fa fa-plus fa-fw"></i></a> -->
    </span>
</h1>
<hr>

<!-- <div class="row">
    <div class="col-md-10 col-md-offset-1">
        <h1>New Employee</h1>

        @if ($errors->any())
        	<div class="alert alert-danger">
        	    <ul>
                    {{ implode('', $errors->all('<li class="error">:message</li>')) }}
                </ul>
        	</div>
        @endif
    </div>
</div> -->

{{ Form::open(array('route' => 'employees.store', 'class' => 'form-horizontal')) }}

<!-- <div class="row">
    <div class="col-md-10 col-md-offset-1">
        <div class="col-md-5">
            

        </div>

        <div class="col-md-5"></div>
    </div>
</div> -->

    <div class="form-group">
        <div class="col-xs-3">
            {{ Form::label('employer', 'Employer:', array('class'=>'control-label')) }}
            {{ Form::text('employer', Input::old('employer'), array('class'=>'form-control', 'placeholder'=>'SMS | AIM')) }}
        </div>
        <div class="col-xs-3">
            {{ Form::label('first_name', 'First Name:', array('class'=>'control-label')) }}
            {{ Form::text('first_name', Input::old('first_name'), array('class'=>'form-control', 'placeholder'=>'First Name')) }}
        </div> 
        <div class="col-xs-3">
            {{ Form::label('middle_name', 'Middle Name:', array('class'=>'control-label')) }}
            {{ Form::text('middle_name', Input::old('middle_name'), array('class'=>'form-control', 'placeholder'=>'Middle Name')) }}
        </div>
        <div class="col-xs-3">
            {{ Form::label('last_name', 'Last Name:', array('class'=>'control-label')) }}
            {{ Form::text('last_name', Input::old('last_name'), array('class'=>'form-control', 'placeholder'=>'Last Name')) }}
        </div>
    </div>

    <div class="form-group">
        <div class="col-xs-3">
            {{ Form::label('id_number', 'ID Number:', array('class'=>'control-label')) }}
            {{ Form::text('id_number', Input::old('id_number'), array('class'=>'form-control', 'data-mask'=>'99-999', 'placeholder'=>'00-000')) }}
        </div>
        <div class="col-xs-3">
            {{ Form::label('date_hired', 'Date Hired:', array('class'=>'control-label')) }}
            {{ Form::text('date_hired', Input::old('date_hired'), array('class'=>'form-control datepicker')) }}
        </div>
        <div class="col-xs-3">
            {{ Form::label('probitionary_date', 'Probitionary Date:', array('class'=>'control-label')) }}
            {{ Form::text('probitionary_date', Input::old('probitionary_date'), array('class'=>'form-control datepicker')) }}
        </div>
        <div class="col-xs-3">
            {{ Form::label('permanency_date', 'Permanency Date:', array('class'=>'control-label')) }}
            {{ Form::text('permanency_date', Input::old('permanency_date'), array('class'=>'form-control datepicker')) }}
        </div>
    </div>

    <div class="form-group">
        <div class="col-xs-3">
            {{ Form::label('contract_period', 'Contract Period:', array('class'=>'control-label')) }}
            {{ Form::text('contract_period', Input::old('contract_period'), array('class'=>'form-control')) }}
        </div>
        <div class="col-xs-3">
            {{ Form::label('designation', 'Designation:', array('class'=>'control-label')) }}
            {{ Form::text('designation', Input::old('designation'), array('class'=>'form-control')) }}
        </div>
        <div class="col-xs-3">
            {{ Form::label('department', 'Department:', array('class'=>'control-label')) }}
            {{ Form::text('department', Input::old('department'), array('class'=>'form-control')) }}
        </div>
        <div class="col-xs-3">
            {{ Form::label('email', 'Email:', array('class'=>'control-label')) }}
            {{ Form::text('email', Input::old('email'), array('class'=>'form-control')) }}
        </div>
    </div>

    <div class="form-group">
        <div class="col-xs-3">
            {{ Form::label('contact_number', 'Contact Number:', array('class'=>'control-label')) }}
            {{ Form::text('contact_number', Input::old('contact_number'), array('class'=>'form-control', 'data-mask'=>'(+63) 999-999-9999')) }}
        </div>
        <div class="col-xs-3">
            {{ Form::label('gender', 'Gender:', array('class'=>'control-label')) }}
            {{ Form::select('gender', array('Male' => 'Male', 'Female' => 'Female'), Input::old('gender'), array('class'=>'form-control chosen-select')) }}
        </div>
        <div class="col-xs-3">
            {{ Form::label('civil_status', 'Civil Status:', array('class'=>'control-label')) }}
            {{ Form::select('civil_status', array('Single' => 'Single', 'Married' => 'Married', 'Widowed' => 'Widowed', 'Annulled' => 'Annulled'), Input::old('civil_status'), array('class'=>'form-control chosen-select')) }}
        </div>
        <div class="col-xs-3">
            {{ Form::label('dependents', 'Dependents:', array('class'=>'control-label')) }}
            {{ Form::select('dependents', array('None'=>'None', '1' => '1', '2' => '2', '3' => '3', '4' => '4', '5' => '5'), Input::old('dependents'), array('class'=>'form-control chosen-select')) }}
        </div>
    </div>

    <div class="form-group">
        <div class="col-xs-3">
            {{ Form::label('hmo', 'HMO:', array('class'=>'control-label')) }}
            {{ Form::text('hmo', Input::old('hmo'), array('class'=>'form-control')) }}
        </div>
        <div class="col-xs-3">
            {{ Form::label('sss', 'SSS:', array('class'=>'control-label')) }}
            {{ Form::text('sss', Input::old('sss'), array('class'=>'form-control', 'data-mask'=>'99-9999999-9')) }}
        </div>
        <div class="col-xs-3">
            {{ Form::label('philhealth', 'Phil Health:', array('class'=>'control-label')) }}
            {{ Form::text('philhealth', Input::old('philhealth'), array('class'=>'form-control', 'data-mask'=>'99-999999999-9')) }}
        </div>
        <div class="col-xs-3">
            {{ Form::label('pagibig', 'Pag-IBIG:', array('class'=>'control-label')) }}
            {{ Form::text('pagibig', Input::old('pagibig'), array('class'=>'form-control', 'data-mask'=>'9999-9999-9999')) }}
        </div>
    </div>

    <div class="form-group">
        <div class="col-xs-3">
            {{ Form::label('tin', 'TIN:', array('class'=>'control-label')) }}
            {{ Form::text('tin', Input::old('tin'), array('class'=>'form-control', 'data-mask'=>'999-999-999')) }}
        </div>
        <div class="col-xs-3">
            {{ Form::label('date_of_birth', 'Date of Birth:', array('class'=>'control-label')) }}
            {{ Form::text('date_of_birth', Input::old('date_of_birth'), array('class'=>'form-control datepicker')) }}
        </div>
        <div class="col-xs-3">
            {{ Form::label('emergency_contact', 'Emergency Contact:', array('class'=>'control-label')) }}
            {{ Form::text('emergency_contact', Input::old('emergency_contact'), array('class'=>'form-control')) }}
        </div>
        <div class="col-xs-3">
            {{ Form::label('emergency_number', 'Emergency Number:', array('class'=>'control-label')) }}
            {{ Form::text('emergency_number', Input::old('emergency_number'), array('class'=>'form-control')) }}
        </div>
    </div>

    <div class="form-group">
        <div class="col-xs-12">
            {{ Form::label('home_address', 'Home Address:', array('class'=>'control-label')) }}
            {{ Form::textarea('home_address', Input::old('home_address'), array('class'=>'form-control', 'rows'=>'3')) }}
        </div>
    </div>

    <div class="form-group">
        <label class="col-xs-12 control-label">&nbsp;</label>
        <div class="col-xs-12">
          {{ Form::submit('Save', array('class' => 'btn btn-primary')) }}
        </div>
    </div>

{{ Form::close() }}

@stop

app/views/employees/index.blade.php
@extends('layouts.scaffold')
@section('main')

<h1 class="">
	<span class="pull-left">
        <a href="/dashboard" class="pull-left"><i class="fa fa-angle-left fa-fw">&nbsp;</i></a>
    </span>
	{{ $heading }} <small>{{ $sub_heading }}</small>
	<span class="pull-right">
		 <a href="/employees/create" class="btn btn-default"><i class="fa fa-plus fa-fw"></i></a>	    
    </span>
</h1>
<hr>

@if ($employees->count())
	<table class="table table-bordered table-hover table-condensed data-table">
		<thead>
			<tr>
				<th>Full Name</th>
				<th>ID Number</th>
				<th>Employer</th>
				<th>Designation</th>
				<th>Department</th>
			</tr>
		</thead>

		<tbody>
			@foreach ($employees as $employee)
				<tr>
					<td>{{ link_to_route('employees.show', $employee->last_name.', '.$employee->first_name.' '.$employee->middle_name, array($employee->id)) }}</td>
					<td>{{{ $employee->id_number }}}</td>
					<td>{{{ $employee->employer }}}</td>
					<td>{{{ $employee->designation }}}</td>
					<td>{{{ $employee->department }}}</td>
				</tr>
			@endforeach
		</tbody>
	</table>
@else
	There are no employees
@endif

@stop

app/views/employees/show.blade.php
@extends('layouts.scaffold')

@section('main')

<h1 class="">
    <span class="pull-left">
         <!-- <a href="/laptops/create" class="btn btn-flat btn-default"><i class="fa fa-plus fa-fw"></i></a> -->
        <a href="/employees" class="pull-left"><i class="fa fa-angle-left fa-fw">&nbsp;</i></a>
    </span>
    {{ $heading }} <small>{{ $sub_heading }}</small>
    <span class="pull-right">
        {{ link_to_route('employees.edit', 'Edit', array($employee->id), array('class' => 'btn btn-flat btn-default')) }}
        {{ Form::open(array('style' => 'display: inline-block;', 'method' => 'DELETE', 'route' => array('employees.destroy', $employee->id))) }}
            {{ Form::submit('Delete', array('class' => 'btn btn-flat btn-danger')) }}
        {{ Form::close() }}
    </span>
</h1>
<hr>

<!-- <h1 class="page-header">{{ $employee->last_name.', '.$employee->first_name.' '.$employee->middle_name }} -->
	<!--  link_to_route('employees.create', <i class="fa fa-plus-sign"></i>, null, array('class' => 'btn btn-success pull-right')) }} -->
	<!-- <a href="/employees" class="btn btn-success pull-right"><i class="fa fa-plus fa-fw">&nbsp;</i>Show All Employees</a> -->
<!-- </h1> -->
<!-- Custom Tabs -->
<div class="nav-tabs-custom">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#profile" data-toggle="tab">Profile</a></li>
        <li><a href="#memos" data-toggle="tab">Memos</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="profile">
            <form class="form-horizontal">
                <div class="form-group">
                    <div class="col-xs-3">
                        {{ Form::label('employer', 'Employer:', array('class'=>'control-label')) }}
                        {{ Form::label('employer', $employee->employer, array('class'=>'form-control')) }}
                    </div>
                    <div class="col-xs-3">
                        {{ Form::label('first_name', 'First Name:', array('class'=>'control-label')) }}
                        {{ Form::label('first_name', $employee->first_name, array('class'=>'form-control')) }}
                    </div>
                    <div class="col-xs-3">
                        {{ Form::label('middle_name', 'Middle Name:', array('class'=>'control-label')) }}
                        {{ Form::label('middle_name', $employee->middle_name, array('class'=>'form-control')) }}
                    </div>
                    <div class="col-xs-3">
                        {{ Form::label('last_name', 'Last Name:', array('class'=>'control-label')) }}
                        {{ Form::label('last_name', $employee->last_name, array('class'=>'form-control')) }}
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-xs-3">
                        {{ Form::label('id_number', 'ID Number:', array('class'=>'control-label')) }}
                        {{ Form::label('id_number', $employee->id_number, array('class'=>'form-control', 'data-mask'=>'99-999')) }}
                    </div>
                    <div class="col-xs-3">
                        {{ Form::label('date_hired', 'Date Hired:', array('class'=>'control-label')) }}
                        {{ Form::label('date_hired', $employee->date_hired, array('class'=>'form-control datepicker')) }}
                    </div>
                    <div class="col-xs-3">
                        {{ Form::label('probitionary_date', 'Probitionary Date:', array('class'=>'control-label')) }}
                        {{ Form::label('probitionary_date', $employee->probitionary_date, array('class'=>'form-control datepicker')) }}
                    </div>
                    <div class="col-xs-3">
                        {{ Form::label('permanency_date', 'Permanency Date:', array('class'=>'control-label')) }}
                        {{ Form::label('permanency_date', $employee->permanency_date, array('class'=>'form-control datepicker')) }}
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-xs-3">
                        {{ Form::label('contract_period', 'Contract Period:', array('class'=>'control-label')) }}
                        {{ Form::label('contract_period', $employee->contract_period, array('class'=>'form-control')) }}
                    </div>
                    <div class="col-xs-3">
                        {{ Form::label('designation', 'Designation:', array('class'=>'control-label')) }}
                        {{ Form::label('designation', $employee->designation, array('class'=>'form-control')) }}
                    </div>
                    <div class="col-xs-3">
                        {{ Form::label('department', 'Department:', array('class'=>'control-label')) }}
                        {{ Form::label('department', $employee->department, array('class'=>'form-control')) }}
                    </div>
                    <div class="col-xs-3">
                        {{ Form::label('email', 'Email:', array('class'=>'control-label')) }}
                        {{ Form::label('email', $employee->email, array('class'=>'form-control')) }}
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-xs-3">
                        {{ Form::label('contact_number', 'Contact Number:', array('class'=>'control-label')) }}
                        {{ Form::label('contact_number', $employee->contact_number, array('class'=>'form-control', 'data-mask'=>'(+63) 999-999-9999')) }}
                    </div>
                    <div class="col-xs-3">
                        {{ Form::label('gender', 'Gender:', array('class'=>'control-label')) }}
                        {{ Form::label('gender', $employee->gender, array('class'=>'form-control')) }}
                    </div>
                    <div class="col-xs-3">
                        {{ Form::label('civil_status', 'Civil Status:', array('class'=>'control-label')) }}
                        {{ Form::label('civil_status', $employee->civil_status, array('class'=>'form-control')) }}
                    </div>
                    <div class="col-xs-3">
                        {{ Form::label('dependents', 'Dependents:', array('class'=>'control-label')) }}
                        {{ Form::label('dependents', $employee->dependents, array('class'=>'form-control')) }}
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-xs-3">
                        {{ Form::label('hmo', 'HMO:', array('class'=>'control-label')) }}
                        {{ Form::label('hmo', $employee->hmo, array('class'=>'form-control')) }}
                    </div>
                    <div class="col-xs-3">
                        {{ Form::label('sss', 'SSS:', array('class'=>'control-label')) }}
                        {{ Form::label('sss', $employee->sss, array('class'=>'form-control', 'data-mask'=>'99-9999999-9')) }}
                    </div>
                    <div class="col-xs-3">
                        {{ Form::label('philhealth', 'Phil Health:', array('class'=>'control-label')) }}
                        {{ Form::label('philhealth', $employee->philhealth, array('class'=>'form-control', 'data-mask'=>'99-999999999-9')) }}
                    </div>
                    <div class="col-xs-3">
                        {{ Form::label('pagibig', 'Pag-IBIG:', array('class'=>'control-label')) }}
                        {{ Form::label('pagibig', $employee->pagibig, array('class'=>'form-control', 'data-mask'=>'9999-9999-9999')) }}
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-xs-3">
                        {{ Form::label('tin', 'TIN:', array('class'=>'control-label')) }}
                        {{ Form::label('tin', $employee->tin, array('class'=>'form-control', 'data-mask'=>'999-999-999-999')) }}
                    </div>
                    <div class="col-xs-3">
                        {{ Form::label('date_of_birth', 'Date of Birth:', array('class'=>'control-label')) }}
                        {{ Form::label('date_of_birth', $employee->date_of_birth, array('class'=>'form-control datepicker')) }}
                    </div>
                    <div class="col-xs-3">
                        {{ Form::label('emergency_contact', 'Emergency Contact:', array('class'=>'control-label')) }}
                        {{ Form::label('emergency_contact', $employee->emergency_contact, array('class'=>'form-control')) }}
                    </div>
                    <div class="col-xs-3">
                        {{ Form::label('emergency_number', 'Emergency Number:', array('class'=>'control-label')) }}
                        {{ Form::label('emergency_number', $employee->emergency_number, array('class'=>'form-control')) }}
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-xs-12">
                        {{ Form::label('home_address', 'Home Address:', array('class'=>'control-label')) }}
                        {{ Form::textarea('home_address', $employee->home_address, array('class'=>'form-control', 'rows'=>'3', 'disabled')) }}
                    </div>
                </div>
            </form>
        </div><!-- /.tab-pane -->

        <div class="tab-pane" id="memos">
            @if ($employee->memos)
                <table class="table table-bordered table-hover table-condensed data-table">
                    <thead>
                        <tr>
                            <th>Device</th>
                            <th>Asset Tag</th>
                            <th>Date Issued</th>
                            <th>Date Returned</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach ($employee->memos as $memo)
                            <tr>
                                <td>{{ link_to_route('laptops.show', $memo->laptop->name, $memo->laptop->id) }}</td>
                                <td>{{{ $memo->laptop->asset_tag }}}</td>
                                <td>{{{ $memo->date_issued }}}</td>
                                <td>{{{ $memo->date_returned }}}</td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            @else
                There are no employees
            @endif

        </div><!-- /.tab-pane -->
    </div><!-- /.tab-content -->
</div><!-- nav-tabs-custom -->




@stop